name: CI

on:
  push:
  pull_request:
  schedule:
    - cron: "0 7 * * 1,3,5"

env:
  CARGO_TERM_COLOR: always

jobs:
  dryrun-tests:
    runs-on: ubuntu-latest
    services:
      sidecar:
        image: parity/substrate-api-sidecar:latest
        ports:
          # Opens tcp port 8080 on the host and service container
          - 8080:8080
        options: >-
          --health-cmd "curl http://localhost:8080/blocks/head | jq"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
  nightly:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install latest nightly
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
          components: rustfmt, clippy

      - name: Run rustfmt
        run: cargo fmt -- --check
      - name: Run clippy
        run: cargo clippy --verbose
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test -- --test-threads=1
  stable:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install latest nightly
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - name: Build
        run: cargo build --verbose
