name: CI

on:
  push:
    branches:
      - **/*
  pull_request:
    branches:
      - **/*
  schedule:
    - cron: "0 7 * * 1,3,5"

env:
  CARGO_TERM_COLOR: always

jobs:
  # Label of the container job
  runner-job:
    # Containers must run in Linux based operating systems
    runs-on: ubuntu-latest

    # Service containers to run with `runner-job`
    services:
      # Label used to access the service container
      sidecar:
        # Docker Hub image
        image: parity/substrate-api-sidecar:latest
        ports:
          # Opens tcp port 8080 on the host and service container
          - 8080:8080
    steps:
      - run: |
          curl -s http://0.0.0.0:8080/blocks/head | jq
  nightly:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install latest nightly
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
          components: rustfmt, clippy

      - name: Run rustfmt
        run: cargo fmt -- --check
      - name: Run clippy
        run: cargo clippy --verbose
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test -- --test-threads=1
  stable:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install latest nightly
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - name: Build
        run: cargo build --verbose
